#!/usr/bin/env bash
#Install nginx
# Update and upgrade packages
apt-get -y update
apt-get -y upgrade

apt-get -y install nginx

# Start nginx service
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello, World!" > /etc/nginx/html/index.html

new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-index.html;

    server_name _;
    location / {
            try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location  /404.html {
        internal;
    }
    if (\$request_filename ~ redirect_me){
    rewrite ^ https://www.youtube.com/@tpauldike permanent;
    }
}
" > /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

nginx -t
nginx -s reload
