#!/usr/bin/env bash

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg <<EOL
# Global settings
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    ssl-default-bind-ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256
    ssl-default-bind-options no-sslv3

# Default settings
defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Frontend configuration
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

# Backend configuration
backend http_back
    balance roundrobin
    server web-01 [20110-web-01 100.26.255.183]:80 check
    server web-02 [20110-web-02 34.224.5.29]:80 check
EOL

# Restart HAProxy to apply the configuration
systemctl restart haproxy

# Enable HAProxy to start on boot
systemctl enable haproxy

# Output to indicate the script has finished
echo "HAProxy has been installed and configured!"

