#!/usr/bin/env bash
# install and configure haproxy on servers

sudo apt-get -y update
apt-get -y install haproxy

# configuration
server_config=\
"
frontend  front
        bind *:80
        mode http
        default_backend back
backend back
        balance roundrobin
        server 20110-web-01 100.26.255.183:80 check
        server 20110-web-02 34.224.5.29:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
