#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 20110-web-01 100.25.137.99:80 check
   server 20110-web-02 54.84.49.34:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
